apiVersion: v1
kind: Service
metadata:
  namespace: fiap
  name: hackathon-video-image-api-svc
spec:
  type: LoadBalancer
  selector:
    app: hackathon-video-image-api
  ports:
    - port: 80
      protocol: TCP
      targetPort: 4080
      name: hackathon-video-image-api-load-balancer
